
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/pay?characterEncoding=utf-8
    username: root
    password: 123
  jpa:
    hibernate:
      format_sql: true
      show_sql: true
      ddl-auto: update
server:
  port: 8080
  
