logging:
  file: D:/
  level: info
server:
  port: 8001
spring:
  freemarker:
    content-type: text/html
    suffix: .html
    template-loader-path: classpath:/templates/
    charset: utf-8
    cache: false
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    settings:
          number_format: "#"
  mvc:
    static-path-pattern: /static/**
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/torison?characterEncoding=utf-8
    username: root
    password: 123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      format_sql: true
      show_sql: true
      ddl-auto: update
  mail:
         host: smtp.qq.com
         username:  294879521@qq.com
         password:  lspkftovkpafbhjd
         properties:
            mail:
              smtp:
                auth: true
                starttls:
                    enable: true
                    required: true