server:
  port: 8011
spring:
    mail:
       host: smtp.qq.com
       username:  294879521@qq.com
       password:  lspkftovkpafbhjd
       properties:
          mail:
            smtp:
              auth: true
              starttls:
                  enable: true
                  required: true


