logging:
  file: D:/
  level: info
server:
  port: 8002
spring:
  freemarker:
    content-type: text/html
    suffix: .html
    template-loader-path: classpath:/templates/
    charset: utf-8
  mvc:
    static-path-pattern: /static/**
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/torison?useUnicode=true&amp&characterEncoding=utf-8
    username: root
    password: 123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    #配置监控统计拦截的filters,去掉之后监控界面sql将无法统计，“wall”用于防火墙
    filters: stat,wall,log4j
    #最大活跃数
    maxActive: 20
    #初始化数量
    initialSize: 1
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
      uri-encoding: UTF-8
  dubbo:
      ##appname: provider
      appname: consumer
      registry: zookeeper://120.79.88.192:2181
      protocol: dubbo
      port: 20881
      scan: com
  mail:
         host: smtp.qq.com
         username:  294879521@qq.com
         password:  lspkftovkpafbhjd
         properties:
            mail:
              smtp:
                auth: true
                starttls:
                    enable: true
                    required: true