logging:
  file: D:/
  level: info
server:
  port: 8002
spring:
  freemarker:
    content-type: text/html
    suffix: .html
    template-loader-path: classpath:/templates/
    charset: utf-8
  mvc:
    static-path-pattern: /static/**
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/torison?useUnicode=true&amp&characterEncoding=utf-8
    username: root
    password: 123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
      uri-encoding: UTF-8
